[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "aifannew"
version = "0.1.7"
description = "ai教学助手本地版"
authors = [
  { name="Johnlin", email="linjiong2020@outlook.com" },
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.14",
    "langchain>=0.3.26",
    "langchain-community>=0.3.27",
    "langgraph>=0.5.1",
    "python-dotenv>=1.1.1",
    "setuptools>=80.9.0",
    "uvicorn>=0.35.0",
    "zhipuai>=2.1.5.20250701",
]

[tool.setuptools.packages.find]
where = ["src"]
